# Generated by Django 5.1.15 on 2026-05-26 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('visibility', models.CharField(choices=[('all', 'All caseworkers / social workers'), ('dept', 'Owning department only')], default='all', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse / partner'), ('guardian', 'Guardian'), ('sibling', 'Sibling')], max_length=16)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, choices=[('deceased', 'Deceased'), ('adoption', 'Adoption / new guardianship'), ('court', 'Court order'), ('other', 'Other')], max_length=16)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='people.person')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='people.person')),
            ],
            options={
                'unique_together': {('person', 'relative', 'relation')},
            },
        ),
    ]
