# Generated by Django 5.1.15 on 2026-05-26 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_person_is_shielded_personaccessgrant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "search_all_persons",
                        "Can search the whole citizen base (intake / borgerservice)",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("name", "Name"), ("cpr", "CPR")],
                        default="name",
                        max_length=8,
                    ),
                ),
                ("term", models.CharField(blank=True, max_length=255)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("break_glass", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched",
                    models.ManyToManyField(
                        blank=True, related_name="search_hits", to="people.person"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
