# Generated by Django 5.1.15 on 2026-06-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_options_searchevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnote',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='people.person'),
        ),
    ]
