# Generated by Django 5.1.15 on 2026-05-26 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'case categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Circumstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('identifier', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(default='https://nalunaarutit.gl/?sc_lang=da', max_length=500)),
                ('snapshot_location', models.CharField(blank=True, max_length=500)),
                ('fetched_at', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('repealed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('legal_basis', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('done', 'Done')], default='new', max_length=16)),
                ('waiting_on', models.CharField(blank=True, max_length=255)),
                ('review_after', models.DateField(blank=True, null=True)),
                ('quiet_reason', models.CharField(blank=True, max_length=255)),
                ('mute_pings', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('owner_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='org.department')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='people.person')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casecategory')),
                ('circumstances', models.ManyToManyField(blank=True, related_name='cases', to='cases.circumstance')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='cases.case')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('call', 'Phone call'), ('meeting', 'Meeting'), ('decision', 'Decision'), ('handoff', 'Handoff')], default='note', max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('what', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='cases.case')),
            ],
            options={
                'ordering': ['done', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseLegalRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('auto', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_links', to='cases.case')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links', to='cases.legalreference')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='legal_refs',
            field=models.ManyToManyField(blank=True, related_name='cases', through='cases.CaseLegalRef', to='cases.legalreference'),
        ),
        migrations.CreateModel(
            name='RegulationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('required', 'Required — must be addressed'), ('recommended', 'Recommended — should be considered')], default='required', max_length=16)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cases.casecategory')),
                ('circumstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='cases.circumstance')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='cases.legalreference')),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
        migrations.AddField(
            model_name='caselegalref',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_links', to='cases.regulationrule'),
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.department')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='org.department')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('support', 'Support'), ('observer', 'Observer')], default='support', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cases.case')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active', 'role'],
                'unique_together': {('case', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('linked', 'Linked — already on the drive'), ('uploaded', 'Uploaded to the drive via this system')], default='linked', max_length=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='people.person')),
            ],
            options={
                'ordering': ['-added_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('case__isnull', False), ('person__isnull', False), _connector='OR'), name='document_has_case_or_person')],
            },
        ),
        migrations.AddConstraint(
            model_name='regulationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('circumstance__isnull', True)), models.Q(('category__isnull', True), ('circumstance__isnull', False)), _connector='OR'), name='regrule_one_trigger'),
        ),
        migrations.AddConstraint(
            model_name='regulationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'reference'), name='uniq_category_reference'),
        ),
        migrations.AddConstraint(
            model_name='regulationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('circumstance__isnull', False)), fields=('circumstance', 'reference'), name='uniq_circumstance_reference'),
        ),
        migrations.AlterUniqueTogether(
            name='caselegalref',
            unique_together={('case', 'reference')},
        ),
    ]
