# Generated by Django 5.1.15 on 2026-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email_from',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('generic', 'Document'), ('email', 'Email')], default='generic', max_length=16),
        ),
    ]
