# Generated by Django 5.1.15 on 2026-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_document_email_from_document_email_sent_at_and_more"),
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casecategory",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Departments that use this category. Leave empty to make it available to every department.",
                related_name="case_categories",
                to="org.department",
            ),
        ),
    ]
