# Generated by Django 5.1.15 on 2026-05-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_documentaccessevent"),
        ("people", "0004_person_is_shielded_personaccessgrant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="direction",
            field=models.CharField(
                choices=[
                    ("in", "Incoming"),
                    ("out", "Outgoing"),
                    ("internal", "Internal"),
                ],
                default="internal",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="journal_number",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="document",
            name="journal_sequence",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="journalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="journalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_journalized",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("journal_number", ""), _negated=True),
                fields=("journal_number",),
                name="uniq_document_journal_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("journal_sequence__isnull", False)),
                fields=("case", "journal_sequence"),
                name="uniq_document_case_journal_sequence",
            ),
        ),
    ]
