# Generated by Django 5.1.15 on 2026-06-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_documentactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='statusevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='cases.case'),
        ),
    ]
