# Generated by Django 5.1.15 on 2026-06-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_caseflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLocator',
            fields=[
            ],
            options={
                'verbose_name': 'case locator',
                'verbose_name_plural': 'case locator',
                'permissions': [('can_locate', 'Can locate cases across departments (routing metadata only)')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cases.case',),
        ),
    ]
