# Generated by Django 5.1.15 on 2026-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_caselocator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('blocked', 'Blocked'), ('done', 'Done'), ('closed', 'Closed (reopenable)')], default='new', max_length=16),
        ),
    ]
