# Generated by Django 5.1.15 on 2026-06-18 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('continues', 'Continues / supersedes'), ('related', 'Related'), ('duplicate', 'Duplicate of')], default='related', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links_made', to=settings.AUTH_USER_MODEL)),
                ('from_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='cases.case')),
                ('to_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_in', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('from_case', 'to_case', 'kind'), name='uniq_case_link'), models.CheckConstraint(condition=models.Q(('from_case', models.F('to_case')), _negated=True), name='case_link_not_self')],
            },
        ),
    ]
